awesome-tab.el
Which makes its window insufficient of space to display all content.
=> Fix: empty header line in magit popup window

README.md, awesome-tab.el
This is more intuitive and consistent with comment in lisp file.
=> fix awesome-tab-hide-tab-function: return t to hide

README.md, awesome-tab.el
See https://github.com/manateelazycat/awesome-tab/pull/38#issuecomment-507155748. This is because background/foreground colors are not specified in terminal. When this happens, colors of tabs are specified according to `frame-background-mode`.
=> fix: make it work when background/foreground colors are not specified.

README.md, awesome-tab.el
- `awesome-tab-build-ivy-source` is removed. I don't know helm but ivy doesn't have a unified source.
- Function was renamed. Usually functions with ivy interface are named `counsel-***`
=> improve ivy interface.

README.md, awesome-tab.el
如题，之前说的 ace jump 的功能做出来了。目前核心功能可以用，但有一些我无法解决的问题，希望得到帮助：
- jump 的时候 tab 会消失。
我的实现是在调用 `awesome-tab-ace-jump` 时，将 `awesome-tab-ace-state` 这个 buffer-local variable 置为 `t`，并创建一个 `ace-strs` 列表，用于存储要用到的 ace 字符串。在 `awesome-tab-buffer-tab-label` 函数中监测 `awesome-tab-ace-state`，如果为 `t` 则在合适的位置插入 ace 字符串。但现在 jump 的时候整个 tab 列就没了，jump 完以后就又出来了。
- 用户输入完以后，`awesome-tab-ace-jump` 会将 `awesome-tab-ace-state` 再置为 `nil`，并刷新显示，这是必要的现场清理工作。但有时用户会用 `C-g` 打断命令，我不知道这时怎么让它清理现场。
- 目前 ace 序列的 face，前景色是在刷新时强行指定为 `error` face 的前景色的，我希望能让用户自定义。但不知为何，如果在 `defface` 处指定 `:foreground (face-foreground 'error)`，启动 emacs 就会报错：`Error running timer ‘require’: (wrong-type-argument stringp (face-foreground (quote error)))`。如果我直接提供一个 `awesome-tab-ace-foreground` 这样的变量，也不能在 `defcustom` 时把它设置成 `(face-foreground 'error)`，就很奇怪。
此外我在 …
=> implement ace jump

README.md, awesome-tab.el
还有一些想商量的：
- 是否需要一个对称的「移动到末尾」命令？我是觉得意义不大，不过可以起到撤回误操作的效果。
- 是否需要一组翻页的命令？我在使用那个 hydra 的时候会觉得翻页比搜索要顺手，不过通常我没有很多 tab，所以移动到开头 / 末尾也是基本一样的效果。
- 是否把 `select-visible-nth-tab` 相关的代码和文档删掉？
=> add move tab to beginning command

awesome-tab.el
In terminal, when background color is not specified, there's this "- - - - -" pattern:
This patch sets `padcolor` to a suitable gray color when this happens.
**Update:** Do not merge now. Please wait a minute. I think maybe I can just not use padcolor if it doesn't have a value, so the color becomes the terminal background color. I will try to do this in a while.
**Update 2:** I found it can't be easily done. I found this: [%- Constructs](https://www.gnu.org/software/emacs/manual/html_node/elisp/_0025_002dConstructs.html#g_t_0025_002dConstructs), so using `- - - - -` to fill up the modeline/header line is the recommended way, or I have to use like a hundred space character to fill it (I'm not sure if this will cause any side effect). If I leave foreground and background color unspecified, …
=> set padcolor when background color is not specified.

awesome-tab.el
我解释一下：我希望能 lazy load `all-the-icons`，所以做了这样的配置：
``` emacs-lisp
(use-package all-the-icons
:defer t)
```
意义基本就是调用 `all-the-icons-autoload` 里面的函数时，才会加载 `all-the-icons`。但这让 `awesome-tab` 的图标显示不工作了。我认为这是由于用 `featurep` 判断包是否已经加载，所以 `all-the-icons` 未加载时，`all-the-icons-icon-for-file` 之类的函数永远不会被执行到，于是就不会触发 `all-the-icons` 的加载。
于是改成了现在的逻辑，就是尝试 `require`，如果 `require` 不到则不执行下面的代码。对 `helm` 和 `ivy` 也做了这件事情，以防类似情况发生。搜索以后发现还有一个 `(featurep 'mac)`。由于没有查到 `mac` 这个包是干什么的（怀疑是不是 aquamacs 之类的东西提供的），就没有动它。
=> fix: work with lazy loaded all-the-icons, ivy and helm.

awesome-tab.el
since https://github.com/manateelazycat/awesome-tab/pull/61, feature is
replaced with require for autoloads. But the former is much faster than
than latter:
(benchmark 1000 '(require 'all-the-icons))"Elapsed time: 11.824975s"
(benchmark 1000 '(provide 'all-the-icons))"Elapsed time: 0.010930s"
If multiple workspaces(either persp or eyebrowser) is switched
frequently, profile-report will tell me that the require expression cost
toom much time. In fact, it just need one "require", but it is executed
many times when switching between dual workspaces.
IMO this require expression should be moved to the ":require" propertity
of awesome-tab-display-icon, so it ensures only one require expression
is executed(when this file is loaded):
> :require
>	VALUE should be a feature symbol.  If you save a …
=> perf: remove unnucessary "require" expression

README.md, awesome-tab.el
- Add an user option for tab index format.
- Only generate background on the fly, so the user can still customize
the faces, the attributes other than background will take effect.
- Add docs about tab index.
=> improve customization on the display of ace-jump and tab index

awesome-tab.el
Emacs 27 shows "package 'cl' is deprecated" after startup, and this is caused by awesome-tab. I checked and found the actually used `cl-` functions are covered by `cl-lib`, so `cl` is not needed.
=> remove package `cl`

awesome-tab.el
Sometimes the header line is occupied by other modes, like `tabulated-list-mode` which is used by `flycheck` and `list-buffers`. It's good to have such a command in these buffers.
=> add: an open tab in current group command

awesome-tab.el
We shouldn't assume the user is familiar with the ido interface. `completing-read` is the standard, and is automatically enhanced by default by ivy or helm, so this is a better choice.
An logic error in awesome-tab-keep-match-buffers-in-current-group is also fixed.
=> remove ido-completing-read calls

awesome-tab.el
fixes `ivy` require which was broken in `a7c1eff36a1caa647505d70b2d9901f93c03a925`
=> fix awesome-tab-counsel-switch-group

awesome-tab.el
For most themes the `default` face is just white or black, and that's not very fascinating.
=> add: user option for active bar color

awesome-tab.el
解决了部分主题中出现 `- - - - - ` 以及前景色偶尔比较诡异的问题。
原因看[这里](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html):
> **:distant-foreground**
>
> Alternative foreground color, a string. This is like :foreground but the color is only used as a foreground when the background color is near to the foreground that would have been used. This is useful for example when marking text (i.e., the region face). If the text has a foreground that is visible with the region face, that foreground is used. If the foreground is near the region face background, :distant-foreground is used instead so the text is readable. 
由于部分主题给 header-line face 设置了这个属性，在 tab 的前景色接近背景色的时候它就会起作用，导致我们设置的 foreground 失效。
=> set distant-foreground for faces

awesome-tab.el
Solves https://github.com/manateelazycat/awesome-tab/issues/77.
有一个莫名其妙的 bug 是在 doom-solarized-light 这个主题下，如果 `awesome-tab-unselected-text-blend` 大于或等于 0.4，unselected tabs 的前景色会变成主题的背景色：
只要换成 0.39 问题就会消失。
doom-themes 还有别的问题（跟这个补丁无关）。你可以从截图看到后面有 `- - - - - ` 这样的细线，这是只要加载一次 doom-themes 里的主题之后就会有的。我看到代码里其实处理了这个的前景色，但不知为什么在 doom-themes 里不起作用。
=> add user options for foreground color

awesome-tab.el
When byte-compiling `awesome-tab.el` a few warnings are reported (I'm using emacs 27.0.91):
```
In toplevel form:
awesome-tab.el:346:20:Warning: assignment to free variable
‘awesome-tab-ace-2-key-seqs’
awesome-tab.el:347:20:Warning: assignment to free variable
‘awesome-tab-ace-1-key-seqs’
In awesome-tab-set-template:
awesome-tab.el:657:11:Warning: defsubst ‘awesome-tab-set-template’ was used
before it was defined
In awesome-tab-line-tab:
awesome-tab.el:1232:11:Warning: defsubst ‘awesome-tab-line-tab’ was used
before it was defined
In awesome-tab-buffer-tab-label:
awesome-tab.el:1258:50:Warning: reference to free variable ‘ace-strs’
In awesome-tab-monitor-window-scroll:
awesome-tab.el:1388:42:Warning: reference to free variable
‘awesome-tab-last-sticky-func-name’ …
```
=> Fix "macro defined too late" error during byte compilation

awesome-tab.el
Emacs 27 has `tab-line` for displaying tabs. A benefit of using it is we can have both `header-line` and `tab-line` displayed. See this:
This is `M-x list-packages`. `tab-line` is used to display tabs, and `header-line` is used to display the header of the table. An obvious benefit is we no more need to hide tabs for such buffers, like `*Flycheck Errors*`.
You may want to:
- Test this patch. I didn't test it thoroughly so there may be problems.
- Edit the hide rules. I choose to show tabs in `*Compile-Log*` and `*Flycheck Errors*` buffers. I don't know `*lsp` and `*epc` in your code, maybe they can benefit from this too.
=> Use tab-line for Emacs 27

awesome-tab.el
The `set-face-attributes` form is not needed.
Besides, there's a little logical inconsistency in this code: If you want to modify `tab-line`, then `awesome-tab-display-line` should be changed to `'tab-line`; if you just want to make sure the display is correct no matter on Emacs 26 or 27, the predicate on Emacs version should be removed. I choose the latter solution.
---
`set-face-attributes` 是不需要的。
此外还有一个小的逻辑问题：如果我们只处理 `tab-line`，那应该直接修改 `'tab-line` 而不是 `awesome-tab-display-line`（因为即使是  Emacs 27，用户可能会自定义成用 `header-line` 显示 tab）；如果我们想保证用户看到的效果是对的，不管是 26 还是 27，那应该把版本的判断拿掉。我选择了后一种做法。
=> Tweak face settings

awesome-tab.el
newest project changed some API.
for example:
(project-current) sometimes return '(vc Git "e:/work/tools/eaf-pdf-viewer/")
=> Adapt to the latest project
